### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by LumaKernel** [violet-ts/violet-infrastructure#36]
GitHub Rest API の認証を理解できていないかもしれないが Bot を入れてもタイトルのエラーが出てきて実行できない。

```
"data": {
    "documentation_url": "https://docs.github.com/rest/reference/issues#create-an-issue-comment",
    "message": "Resource not accessible by integration"
 },
```

```
 "stack": "HttpError: Resource not accessible by integration\n    at /node_modules/.pnpm/@octokit+request@5.6.2/node_modules/@octokit/request/dist-src/fetch-wrapper.js:68:27\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at vae (/node_modules/.pnpm/@octokit+auth-app@3.6.1/node_modules/@octokit/auth-app/dist-src/hook.js:70:16)\n    at T9e (/var/src/app/webhooks.ts:116:26)\n    at /var/src/app/webhooks.ts:181:9",
```

https://ap-northeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fviolet-bot-github-bot-13ee1n/log-events/2021$252F11$252F03$252F$255B$2524LATEST$255Da7b6e95490c44c2f8ce99f72815eb87c

**Comment by LumaKernel** [comment]
自分の org に追加して確かめてみる。

**Comment by LumaKernel** [comment]
なるほど。 Bot のインストールID は全部違うみたいだ。

**Comment by LumaKernel** [comment]
ID は webhook のイベントからわかりそう。

**Comment by LumaKernel** [comment]
on any ではわからないので dynamodb に入れておこう

**Comment by LumaKernel** [comment]
https://github.com/violet-ts/violet/pull/63#issuecomment-960567560
